{
 "title": "Database Backup Reports",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES ON telegraf FROM \"sqlserver_server_properties\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Full Backup ( Size )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_database]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_backup",
     "query": "SELECT mean(\"size_bytes\")  / 1024 / 1024  FROM \"sqlserver_backup\" WHERE \"host\" =~ /^(?i)$Host$/ AND \"backuptype\" = 'FullDatabase' AND $timeFilter GROUP BY time($__interval), \"database\" fill(none)",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^(?i)$Instance$/" },
      { "condition": "AND", "key": "backuptype", "operator": "=", "value": "FullDatabase" }
     ]
    }
   ]
  },
  {
   "title": "Full Backup ( Duration )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_database]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_backup",
     "query": "SELECT max(\"duration_sec\") FROM \"sqlserver_backup\" WHERE \"host\" =~ /^(?i)$Host$/ AND \"backuptype\" = 'FullDatabase' AND $timeFilter GROUP BY time($__interval), \"database\" fill(none)",
     "select": [
      [
       { "params": [ "duration_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^(?i)$Instance$/" },
      { "condition": "AND", "key": "backuptype", "operator": "=", "value": "FullDatabase" }
     ]
    }
   ]
  },
  {
   "title": "Diff Backup ( Size )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_database]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_backup",
     "query": "SELECT mean(\"size_bytes\")  / 1024 / 1024  FROM \"sqlserver_backup\" WHERE \"host\" =~ /^(?i)$Host$/  AND \"backuptype\" = 'DiffDatabase' AND $timeFilter GROUP BY time($__interval), \"database\" fill(none)",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024 / 1024 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^(?i)$Instance$/" },
      { "condition": "AND", "key": "backuptype", "operator": "=", "value": "DiffDatabase" }
     ]
    }
   ]
  },
  {
   "title": "Diff Backup ( Duration )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_database]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_backup",
     "query": "SELECT max(\"duration_sec\") FROM \"sqlserver_backup\" WHERE \"host\" =~ /^(?i)$Host$/ AND \"backuptype\" = 'DiffDatabase' AND $timeFilter GROUP BY time($__interval), \"database\" fill(none)",
     "select": [
      [
       { "params": [ "duration_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^(?i)$Instance$/" },
      { "condition": "AND", "key": "backuptype", "operator": "=", "value": "DiffDatabase" }
     ]
    }
   ]
  },
  {
   "title": "Log Backup ( Size )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_database]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_backup",
     "query": "SELECT max(\"size_bytes\")  / 1024 / 1024  FROM \"sqlserver_backup\" WHERE \"host\" =~ /^(?i)$Host$/ AND \"backuptype\" = 'Log' AND $timeFilter GROUP BY time($__interval), \"database\" fill(none)",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1024 / 1024 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^(?i)$Instance$/" },
      { "condition": "AND", "key": "backuptype", "operator": "=", "value": "Log" }
     ]
    }
   ]
  },
  {
   "title": "Log Backup ( Duration )",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_database]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_backup",
     "query": "SELECT max(\"duration_sec\") FROM \"sqlserver_backup\" WHERE \"host\" =~ /^(?i)$Host$/ AND \"backuptype\" = 'Log' AND $timeFilter GROUP BY time($__interval), \"database\" fill(none)",
     "select": [
      [
       { "params": [ "duration_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^(?i)$Instance$/" },
      { "condition": "AND", "key": "backuptype", "operator": "=", "value": "Log" }
     ]
    }
   ]
  }
 ]
}